# This is a basic workflow to help you get started with Actions

name: Howest CIA Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '3.1.100' #SDK Version to use
        
    - name: Try to build my code
      run: dotnet build

    - name: Run Unit tests on my code
      run: dotnet test -v n         

    - name: Push to heroku
      env: 
        HEROKU_REGISTRY_URL: registry.heroku.com
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
            docker build -t cia-deployment-dries .
            heroku container:login
            docker tag cia-deployment-dries registry.heroku.com/cia-deployment-dries/web
            docker push registry.heroku.com/cia-deployment-dries/web
            heroku container:release web -a cia-deployment-dries
